package com.base.demo.domain;

import javax.persistence.*;

@Table(name = "t_base_param_info")
public class ParamInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.type_code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.parent_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.id
     *
     * @return the value of t_base_param_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.id
     *
     * @param id the value for t_base_param_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.code
     *
     * @return the value of t_base_param_info.code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.code
     *
     * @param code the value for t_base_param_info.code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.name
     *
     * @return the value of t_base_param_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.name
     *
     * @param name the value for t_base_param_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.type_code
     *
     * @return the value of t_base_param_info.type_code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.type_code
     *
     * @param typeCode the value for t_base_param_info.type_code
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.parent_id
     *
     * @return the value of t_base_param_info.parent_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.parent_id
     *
     * @param parentId the value for t_base_param_info.parent_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_info.remark
     *
     * @return the value of t_base_param_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_info.remark
     *
     * @param remark the value for t_base_param_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}