package com.base.demo.domain;

import java.util.Date;
import javax.persistence.*;

@Table(name = "t_base_role_info")
public class RoleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.type
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Date createTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Date updateTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.id
     *
     * @return the value of t_base_role_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.id
     *
     * @param id the value for t_base_role_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.name
     *
     * @return the value of t_base_role_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.name
     *
     * @param name the value for t_base_role_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.type
     *
     * @return the value of t_base_role_info.type
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.type
     *
     * @param type the value for t_base_role_info.type
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.remark
     *
     * @return the value of t_base_role_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.remark
     *
     * @param remark the value for t_base_role_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.union_id
     *
     * @return the value of t_base_role_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.union_id
     *
     * @param unionId the value for t_base_role_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.create_user_id
     *
     * @return the value of t_base_role_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.create_user_id
     *
     * @param createUserId the value for t_base_role_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.create_ts
     *
     * @return the value of t_base_role_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.create_ts
     *
     * @param createTs the value for t_base_role_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.update_user_id
     *
     * @return the value of t_base_role_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.update_user_id
     *
     * @param updateUserId the value for t_base_role_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_info.update_ts
     *
     * @return the value of t_base_role_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_info.update_ts
     *
     * @param updateTs the value for t_base_role_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }
}