package com.base.demo.domain;

import javax.persistence.*;

@Table(name = "t_base_role_resource_rel")
public class RoleResourceRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_resource_rel.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_resource_rel.role_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_role_resource_rel.resource_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_resource_rel.id
     *
     * @return the value of t_base_role_resource_rel.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_resource_rel.id
     *
     * @param id the value for t_base_role_resource_rel.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_resource_rel.role_id
     *
     * @return the value of t_base_role_resource_rel.role_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_resource_rel.role_id
     *
     * @param roleId the value for t_base_role_resource_rel.role_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_role_resource_rel.resource_id
     *
     * @return the value of t_base_role_resource_rel.resource_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_role_resource_rel.resource_id
     *
     * @param resourceId the value for t_base_role_resource_rel.resource_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}