package com.base.demo.domain;

import java.util.Date;
import javax.persistence.*;

@Table(name = "t_base_union_info")
public class UnionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.domail_url
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String domailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.create_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.create_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private Date createTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.update_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_union_info.update_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    private Date updateTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.id
     *
     * @return the value of t_base_union_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.id
     *
     * @param id the value for t_base_union_info.id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.name
     *
     * @return the value of t_base_union_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.name
     *
     * @param name the value for t_base_union_info.name
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.domail_url
     *
     * @return the value of t_base_union_info.domail_url
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getDomailUrl() {
        return domailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.domail_url
     *
     * @param domailUrl the value for t_base_union_info.domail_url
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setDomailUrl(String domailUrl) {
        this.domailUrl = domailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.remark
     *
     * @return the value of t_base_union_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.remark
     *
     * @param remark the value for t_base_union_info.remark
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.create_user_id
     *
     * @return the value of t_base_union_info.create_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.create_user_id
     *
     * @param createUserId the value for t_base_union_info.create_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.create_ts
     *
     * @return the value of t_base_union_info.create_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.create_ts
     *
     * @param createTs the value for t_base_union_info.create_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.update_user_id
     *
     * @return the value of t_base_union_info.update_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.update_user_id
     *
     * @param updateUserId the value for t_base_union_info.update_user_id
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_union_info.update_ts
     *
     * @return the value of t_base_union_info.update_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_union_info.update_ts
     *
     * @param updateTs the value for t_base_union_info.update_ts
     *
     * @mbg.generated Tue Apr 17 23:19:46 CST 2018
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }
}