package com.base.demo.domain;

import java.util.Date;
import javax.persistence.*;

@Table(name = "t_base_user_info")
public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.password
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.mobile_no
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.salt
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.authe_status
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String autheStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.is_valid
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Date createTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_user_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    private Date updateTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.id
     *
     * @return the value of t_base_user_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.id
     *
     * @param id the value for t_base_user_info.id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.name
     *
     * @return the value of t_base_user_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.name
     *
     * @param name the value for t_base_user_info.name
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.password
     *
     * @return the value of t_base_user_info.password
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.password
     *
     * @param password the value for t_base_user_info.password
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.mobile_no
     *
     * @return the value of t_base_user_info.mobile_no
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.mobile_no
     *
     * @param mobileNo the value for t_base_user_info.mobile_no
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.salt
     *
     * @return the value of t_base_user_info.salt
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.salt
     *
     * @param salt the value for t_base_user_info.salt
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.remark
     *
     * @return the value of t_base_user_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.remark
     *
     * @param remark the value for t_base_user_info.remark
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.union_id
     *
     * @return the value of t_base_user_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.union_id
     *
     * @param unionId the value for t_base_user_info.union_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.authe_status
     *
     * @return the value of t_base_user_info.authe_status
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getAutheStatus() {
        return autheStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.authe_status
     *
     * @param autheStatus the value for t_base_user_info.authe_status
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setAutheStatus(String autheStatus) {
        this.autheStatus = autheStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.is_valid
     *
     * @return the value of t_base_user_info.is_valid
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.is_valid
     *
     * @param isValid the value for t_base_user_info.is_valid
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.create_user_id
     *
     * @return the value of t_base_user_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.create_user_id
     *
     * @param createUserId the value for t_base_user_info.create_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.create_ts
     *
     * @return the value of t_base_user_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.create_ts
     *
     * @param createTs the value for t_base_user_info.create_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.update_user_id
     *
     * @return the value of t_base_user_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.update_user_id
     *
     * @param updateUserId the value for t_base_user_info.update_user_id
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_user_info.update_ts
     *
     * @return the value of t_base_user_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_user_info.update_ts
     *
     * @param updateTs the value for t_base_user_info.update_ts
     *
     * @mbg.generated Wed Apr 18 17:21:55 CST 2018
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }
}